// lib/compiler.mjs
import { readdirSync, readFileSync, writeFileSync, existsSync, statSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { parseYaml, toFrontmatter } from './yaml-lite.mjs';
import { listRules, renderRulesSection, compileRules } from './rules.mjs';
import { compileIgnore } from './ignore.mjs';

export function listSkills(targetDir) {
  const skillsDir = join(targetDir, 'skills');
  if (!existsSync(skillsDir)) return [];
  return readdirSync(skillsDir)
    .filter((n) => statSync(join(skillsDir, n)).isDirectory())
    .filter((n) => existsSync(join(skillsDir, n, 'skill.yaml')))
    .sort()
    .map((name) => {
      const dir = join(skillsDir, name);
      const meta = parseYaml(readFileSync(join(dir, 'skill.yaml'), 'utf8')) || {};
      const promptPath = join(dir, 'prompt.md');
      const prompt = existsSync(promptPath) ? readFileSync(promptPath, 'utf8') : '';
      return { name, whenToUse: meta['when-to-use'] || '', description: meta.description || '', prompt, uses: meta.uses || {}, argumentHint: meta['argument-hint'] || '' };
    });
}

export function renderAgentsMd(skills, rules = []) {
  const lines = [
    '# AGENTS.md',
    '',
    '> Generated by Agent Plugin Kit gene compilation, for any AI coding host to read.',
    '',
    '## Skills',
    '',
  ];
  for (const s of skills) {
    lines.push(`### ${s.name}`, '', s.description, '',
      `- When to use: ${s.whenToUse}`, `- Location: \`skills/${s.name}/\``);
    const u = s.uses || {};
    const parts = [];
    if (u.mcp && u.mcp.length) parts.push(`mcp: ${u.mcp.join(', ')}`);
    if (u.permissions && u.permissions.length) parts.push(`permissions: ${u.permissions.join(', ')}`);
    if (u.subagents && u.subagents.length) parts.push(`subagents: ${u.subagents.join(', ')}`);
    if (parts.length) lines.push(`- Depends on: ${parts.join(' · ')}`);
    lines.push('');
  }
  const rulesSection = renderRulesSection(rules);
  if (rulesSection) lines.push(rulesSection, '');
  return lines.join('\n');
}

export function compileAgentsMd(targetDir) {
  const skills = listSkills(targetDir);
  writeFileSync(join(targetDir, 'AGENTS.md'), renderAgentsMd(skills, listRules(targetDir)), 'utf8');
  return skills.length;
}

// ---- host-specific compilation -------------------------------------------
// Compile each gene skill into the native format each host actually reads. Scripts/knowledge
// still reference the project-relative path skills/<name>/... (the real skill), not copied. Only
// the files corresponding to gene skills are written.

function fullDescription(s) {
  return s.whenToUse ? `${s.description} ${s.whenToUse}`.trim() : s.description;
}

// Claude Code reads .claude/skills/<name>/SKILL.md (it does not read AGENTS.md)
export function renderClaudeSkill(s) {
  const fmObj = { description: fullDescription(s) };
  const perms = (s.uses && s.uses.permissions) || [];
  if (perms.length) fmObj['allowed-tools'] = perms.join('|');   // gene #5: self-description -> real permissions
  const fm = toFrontmatter(fmObj);
  return `---\n${fm}\n---\n\n${s.prompt}`;
}

export function compileClaudeSkills(targetDir) {
  const skills = listSkills(targetDir);
  for (const s of skills) {
    const dir = join(targetDir, '.claude', 'skills', s.name);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'SKILL.md'), renderClaudeSkill(s), 'utf8');
  }
  return skills.length;
}

// Cursor reads .cursor/rules/<name>.mdc (alwaysApply:false -> the agent selects it by relevance)
export function renderCursorRule(s) {
  const fm = toFrontmatter({ description: fullDescription(s), alwaysApply: false });
  return `---\n${fm}\n---\n\n${s.prompt}`;
}

export function compileCursorRules(targetDir) {
  const skills = listSkills(targetDir);
  if (skills.length) mkdirSync(join(targetDir, '.cursor', 'rules'), { recursive: true });
  for (const s of skills) {
    writeFileSync(join(targetDir, '.cursor', 'rules', `${s.name}.mdc`), renderCursorRule(s), 'utf8');
  }
  return skills.length;
}

// Compile a skill's <skill>/subagents/*.md into the project's .claude/agents/<skill>-<file> (Claude project subagents)
export function compileSubagents(targetDir) {
  let count = 0;
  for (const s of listSkills(targetDir)) {
    const subDir = join(targetDir, 'skills', s.name, 'subagents');
    if (!existsSync(subDir)) continue;
    const agentsDir = join(targetDir, '.claude', 'agents');
    mkdirSync(agentsDir, { recursive: true });
    for (const f of readdirSync(subDir).filter((n) => n.endsWith('.md'))) {
      writeFileSync(join(agentsDir, `${s.name}-${f}`), readFileSync(join(subDir, f), 'utf8'));
      count += 1;
    }
  }
  return count;
}

// One source -> AGENTS.md (open standard) + Claude-native SKILL.md + Cursor-native + Claude subagents
//        + rules (CLAUDE.md / Cursor) + ignore (.gitignore / .cursorignore / .geminiignore)
export function compileAll(targetDir) {
  // both skills and rules land in .cursor/rules/<name>.mdc; same name would overwrite each other -> fail early, don't silently drop data
  const skillNames = new Set(listSkills(targetDir).map((s) => s.name));
  const clash = listRules(targetDir).map((r) => r.name).filter((n) => skillNames.has(n));
  if (clash.length) {
    throw new Error(`name collision between skill and rule: ${clash.join(', ')} (names must be unique across skills + rules; both compile to .cursor/rules/<name>.mdc)`);
  }
  compileAgentsMd(targetDir);
  compileClaudeSkills(targetDir);
  compileSubagents(targetDir);
  compileRules(targetDir);
  compileIgnore(targetDir);
  return compileCursorRules(targetDir);   // return the skill count (preserve the existing contract)
}
